### ISSUE TITLE
Problem with dependency check

### ISSUE THREAD

**Issue by rdmueller** [aim42/htmlSanityCheck#148]
When using the [com.github.ben-manes.versions gradle plugin version "0.14.0"](https://plugins.gradle.org/plugin/com.github.ben-manes.versions) to check for newer dependency versions of my gradle build, the tasks fails for the htmlSanityCheck plugin with the following message:

```
Failed to determine the latest version for the following dependencies (use --info for details):
 - gradle.plugin.org.aim42:htmlSanityCheck
The exception that is the cause of unresolved state: Could not find any matches for gradle.plugin.org.aim42:htmlSanityCheck:+ as no versions of gradle.plugin.org.aim42:htmlSanityCheck are available.
Searched in the following locations:
    https://plugins.gradle.org/m2/gradle/plugin/org/aim42/htmlSanityCheck/maven-metadata.xml
    https://plugins.gradle.org/m2/gradle/plugin/org/aim42/htmlSanityCheck/ 
```

Is there a chance to fix this within this project?
btw: I use htmlSanityCheck in V0.9.6

**Comment by double16** [comment]
I am using the same versions plugin, '0.14.0', in a project with htmlSanityCheck 0.9.6 and it's working well. Can you give the applicable snippets from your Gradle build? `buildscript`, `dependencies`, how you are applying the plugin either via `plugins` or `apply` ?

**Comment by rdmueller** [comment]
interesting. 
So, this is my build file: https://github.com/rdmueller/docToolchain/blob/master/build.gradle
Maybe the big difference is that I do not define repositories?
I will give this a try...

**Comment by rdmueller** [comment]
hm. still the same problem. Do you have an example build file which works? I would then try to investigate a bit more...

**Comment by rdmueller** [comment]
hm. independent from how I reference the plugin (`plugins` or `apply`) I get the same error.

But I also just found out that
https://plugins.gradle.org/m2/gradle/plugin/org/aim42/htmlSanityCheck/0.9.3/htmlSanityCheck-0.9.3.pom
is resolved as a download but
https://plugins.gradle.org/m2/gradle/plugin/org/aim42/htmlSanityCheck/
(the URL which the `dependencyUpdate` tries to resolve) is redirectred to
https://jcenter.bintray.com/gradle/plugin/org/aim42/htmlSanityCheck/
which results in a `path not found`.

don't know what's going on here...

**Comment by double16** [comment]
https://github.com/double16/pet-store is an example that works. The htmlSanityCheck plugin is in the `staticsite` sub-project.

You might need to add `maven { url "https://plugins.gradle.org/m2/" }` to your buildscript repositories.

We're using the latest (or very close to it) Gradle publishing plugin to publish, so it should be working similarly to other Gradle plugins.

**Comment by gernotstarke** [comment]
@rdmueller  - can I close this one? Seems resolved..

**Comment by rdmueller** [comment]
hm. not really resolved, but it seems that I am the only one with this problem and it is a minor problem... so I close it for now...
